// Author: Haowen Jiang
// Date: 30/05/2024
// Display the formula generated by chatgpt correctly 
// in the markdown file
#include <stdio.h>
#include <stdlib.h>
void readFile(const char *filename, char **content, long *length) {
    FILE *file = fopen(filename, "rb");
    if (file == NULL) {
        fprintf(stderr, "无法打开文件 %s 进行读取\n", filename);
        exit(1);
    }

    fseek(file, 0, SEEK_END);
    *length = ftell(file);
    fseek(file, 0, SEEK_SET);

    *content = (char *)malloc(*length + 1);
    if (*content == NULL) {
        fprintf(stderr, "内存分配失败\n");
        exit(1);
    }

    fread(*content, 1, *length, file);
    (*content)[*length] = '\0';

    fclose(file);
}

void writeFile(const char *filename, const char *content) {
    FILE *file = fopen(filename, "wb");
    if (file == NULL) {
        fprintf(stderr, "无法打开文件 %s 进行写入\n", filename);
        exit(1);
    }

    fwrite(content, 1, strlen(content), file);
    fclose(file);
}

void replaceChar(char *str, char newChar) {
    while (*str) {
        if (*str == '\\' && (*(str+1) == '(' || *(str+1) == '[')) {
            if(*(str+1) == '(' ) {
                *(str+2) = newChar;
            }
            else {
                *str = '$';
                *(str+1) = '$';
            }
           
        }
        if (*str == '\\' && (*(str+1) == ')' || *(str+1) == ']')) {     
            if(*(str+1) == ')' ) {
                *(str) = newChar;
            }
            else {
                *str = '$';
                *(str+1) = '$';
            }
        }
        str++;
    }
}

int main(int argc, char** argv) {
    char *content;
    long length;
    readFile(argv[1], &content, &length);
    replaceChar(content,'$');
    writeFile("output.md", content);
    free(content);
    printf("Output success\r\n");

    return 0;
}
